### ISSUE TITLE
Missing example scenes

### ISSUE THREAD

**Issue by hyakugei** [uweenukr/Insight#1]
But the .meta files were committed. (Unity 2017.4.16f1, OSX, Latest Mirror from Asset Store)

<img width="599" alt="screenshot 2018-12-20 14 10 51" src="https://user-images.githubusercontent.com/136433/50305570-3770f800-0461-11e9-965c-7a8a0a700234.png">

**Comment by uweenukr** [comment]
I was making a messy refactor. Things should be more stable now.

**Comment by uweenukr** [comment]
Can you confirm that the examples are now working?

**Comment by hyakugei** [comment]
All good.
