### ISSUE TITLE
ProcessSpawner not correctly dispatching processes

### ISSUE THREAD

**Issue by Paradoks-Studio** [uweenukr/Insight#24]
i don't have gitHub so i drop it there:
need testing.

in ProcessSpawner.cs - bool InternalStartNewProcess(RequestSpawnStartMsg spawnProperties)

**switch** 
            
>//If registered to a master. Notify it of the current thread utilization
>if (client != null)
>{
>    client.Send(new SpawnerStatusMsg() { CurrentThreads = GetRunningProcessCount() });
>}

>spawnerProcesses[thisPort] = new RunningProcessContainer() { process = p, pid = p.Id, uniqueID = spawnProperties.UniqueID};

**to**
            
>spawnerProcesses[thisPort] = new RunningProcessContainer() { process = p, pid = p.Id, uniqueID = spawnProperties.UniqueID };

>//If registered to a master. Notify it of the current thread utilization
>if (client != null)
>{
>    client.Send(new SpawnerStatusMsg() { CurrentThreads = GetRunningProcessCount() });
>}

**Comment by uweenukr** [comment]
Fixed in commit https://github.com/uweenukr/Insight/commit/131155f0de8e3e02e68dc646fb714beb0de9852f
